---
- name: Install software (Debian-based OS)
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: yes
    cache_valid_time: 900
  with_items: "{{ software_list }}"
  when: ansible_os_family == 'Debian'
